name: Check EMAIL

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Start Process
        run: echo "Process Starting"

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Run Email Code
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: python send_email.py
