name: daily Report

on:
    workflow_dispatch:
#   push:
#     branches:
#       - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: echo "Hello World"
